{% set name = "mlx-vlm" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlx_vlm-{{ version }}.tar.gz
  sha256: 039a8d9afa9c1aa4f753eb3658199350aaaac51c6ad195540289911ff2021f2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - datasets >=2.19.1
    - tqdm >=4.66.2
    - scipy ==1.13.1
    - gradio >=4.44.0
    - python >={{ python_min }}
    - mlx >=0.22.0
    - mlx-lm >=0.4.0
    - numpy >=1.23.4
    - transformers >=4.47.1
    - pytorch
    - huggingface_hub
    - pillow >=10.3.0
    - requests >=2.31.0

test:
  imports:
    - mlx_vlm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Blaizzy/mlx-vlm
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
