{% set name = "mlx-vlm" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlx_vlm-{{ version }}.tar.gz
  sha256: 10044d5d3ab9bbb0bf0f4cd836a39fd8751bac44452a2a6735dc98925fd228fb

build:
  noarch: python
  script:
    - sed -i 's/opencv-python==4.10.0.84/opencv-python>=4.10,<4.11/g' requirements.txt
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - sed
  run:
    - fastapi >=0.95.1
    - mlx-audio
    - opencv ==4.10.0.84
    - soundfile >=0.13.1
    - py-opencv 4.10.0.*
    - datasets >=2.19.1
    - tqdm >=4.66.2
    - scipy >=1.15.3
    - gradio >=5.19.0
    - python >={{ python_min }}
    - mlx >=0.26.0
    - mlx-lm >=0.23.0
    - numpy
    - transformers >=4.53.0
    - pytorch
    - huggingface_hub
    - pillow >=10.3.0
    - requests >=2.31.0

test:
  imports:
    - mlx_vlm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Blaizzy/mlx-vlm
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
