{% set name = "mlx-vlm" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlx_vlm-{{ version }}.tar.gz
  sha256: caea7eee0c870d4cbead95074d28bc65f9c316dd396e5ecca84edcde83d51a9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - datasets >=2.19.1
    - tqdm >=4.66.2
    - scipy ==1.13.1
    - gradio >=4.44.0
    - python >=3.8
    - mlx >=0.18.1
    - mlx-lm >=0.4.0
    - numpy >=1.23.4
    - transformers >=4.47.1
    - pytorch
    - huggingface_hub
    - pillow >=10.3.0
    - requests >=2.31.0

test:
  imports:
    - mlx_vlm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blaizzy/mlx-vlm
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
