{% set name = "mlx-vlm" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlx_vlm-{{ version }}.tar.gz
  sha256: 2154b3cfb731c66b2179668079d683f1e647b6ff93a1148ccfc72b9df6bcd28a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - scipy ==1.13.1
    - gradio
    - python >=3.8
    - mlx >=0.14
    - mlx-lm >=0.4.0
    - numpy
    - transformers >=4.39.3
    - pytorch
    - huggingface_hub
    - pillow
    - requests

test:
  imports:
    - mlx_vlm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blaizzy/mlx-vlm
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
