{% set name = "mlx-vlm" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlx_vlm-{{ version }}.tar.gz
  sha256: 057a1c02e7eed693667ced8760548fa3f194b9e2b0e777aaaac6fa944876117c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - scipy ==1.13.1
    - gradio >=4.44.0
    - python >=3.8
    - mlx >=0.18.0
    - mlx-lm >=0.4.0
    - numpy
    - transformers >=4.45.1
    - pytorch
    - huggingface_hub
    - pillow
    - requests

test:
  imports:
    - mlx_vlm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blaizzy/mlx-vlm
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
