{% set name = "mlx-vlm" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlx_vlm-{{ version }}.tar.gz
  sha256: 66dcd882040337fe1fe4e5cbe4a2c974bac423a29de1451e968f3859850bcc96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - mlx >=0.8.0
    - mlx-lm >=0.4.0
    - numpy
    - transformers
    - pytorch
    - huggingface_hub
    - pillow
    - requests

test:
  imports:
    - mlx_vlm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blaizzy/mlx-vlm
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
