schema_version: 1

context:
  name: mlx-vlm
  version: "0.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mlx_vlm-${{ version }}.tar.gz
  sha256: bbb251a514d995849c9f67acc491467767704c393c9399ada11602cd88facf36

build:
  number: 0
  noarch: python
  script:
    - sed -i 's/opencv-python==4.10.0.84/opencv-python>=4.10,<4.11/g' requirements.txt
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - sed
  run:
    - py-opencv 4.10.0.*
    - datasets >=2.19.1
    - tqdm >=4.66.2
    - scipy ==1.13.1
    - gradio >=5.19.0
    - python >=${{ python_min }}
    - mlx >=0.26.0
    - mlx-lm >=0.25.1
    - numpy >=1.23.4
    - transformers >=4.51.3
    - pytorch
    - huggingface_hub
    - pillow >=10.3.0
    - requests >=2.31.0
    - fastapi >=0.95.1

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - mlx_vlm

about:
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Blaizzy/mlx-vlm

extra:
  recipe-maintainers:
    - xhochy
